### ISSUE TITLE
Google Docs will begin counting against storage caps June 1, 2021

### ISSUE THREAD

**Issue by johnfernow** [stewartmcgown/uds#101]
**Is your feature request related to a problem? Please describe.**
Starting June 1, 2021, Google will count Docs, Sheets, Slides, Drawings, Forms and Jamboard files against the user's storage quota. [Source.](https://www.theverge.com/2020/11/11/21560810/google-photos-unlimited-cap-free-uploads-15gb-ending)

**Describe the solution you'd like**
All photos and documents uploaded before June 1st will not count against that 15GB cap. It's unclear if updating previously uploaded documents will cause them to count against the storage quota. If updating them doesn't count against the quota, this project could be updated to create tons of empty documents to use later on. E.g., if it created 20,000 Google Slide files for a user before June 1, 2021, that'd allow the user to store 1TB by updating those empty Slide files (though only _if_ updating those files doesn't count against the quota, which is still unknown.)

**Describe alternatives you've considered**
If updating previously uploaded files causes them to count against the quota, then there's nothing that can be done to fix this issue, so the only thing that can be done is update the README about this unfortunate news (either way the README will have to be updated to address this, as even in the best case, it needs to be mentioned that this tool needs to be ran before June 1, 2021.)

**Additional context**
I put this as a feature request, as it's not a bug with the project itself, rather a change on Google's end, and wasn't sure how the contributors wanted to move forward with this. Very sad news :(

**Comment by stewartmcgown** [comment]
Message received 🖖

"Stop doing dumb shit with Google APIs."

**Comment by BluelyTASer** [comment]
So if you have 1 TB of Data that you want to upload to google drive, do it right now before June 1, 2021!

**Comment by sammyhass** [comment]
Wow, got a mention in the verge, that's pretty neat. We had a great run folks!

**Comment by sammyhass** [comment]
Closing this issue 40ad5ff shows warning in README.md - Everyone get your uploads in before June!
