### ISSUE TITLE
Major functionality issue

### ISSUE THREAD

**Issue by 667xxx** [stewartmcgown/uds#114]
If Google Drive counts these docs towards your storage quota, and the size of the encoded file is always larger than the original. What is the point?

**Comment by stewartmcgown** [comment]
Lol

**Comment by sammyhass** [comment]
Google has now made this project impossible to maintain as docs *now* DO count toward your quota, up until June 2021, this was possible. 

Further Reading: https://support.google.com/googleone/answer/9312312?hl=en-GB
