### ISSUE TITLE
Using on mac, invalid syntax error, line 226

### ISSUE THREAD

**Issue by TRD0118** [stewartmcgown/uds#13]
I've successfully installed all the things I need to from requirements.txt, I've made sure the Python version I'm running allows for "f" lines (it's 3.7.1), but I'm still getting a syntax error:

 File "uds.py", line 226
    path = f"{get_downloads_folder()}/{metadata['name']}"
                                                                                           

Any help would be appreciated.

**Comment by sirpilsofd** [comment]
I'm getting the same error msg, but I'm running ubuntu server 16.04 and python version 2.7

**Comment by de-odex** [comment]
@sirpilsofd
The project is python 3.6 up only, as stated in a former issue #6

**Comment by stewartmcgown** [comment]
you need [Python 3](https://www.python.org/downloads/)

**Comment by de-odex** [comment]
@stewartmcgown 
but @TRD0118 did mention he was on 3.7.1

**Comment by sirpilsofd** [comment]
OK, Used python 3 to run uds.py but still get the same error.

**Comment by stewartmcgown** [comment]
closing now. if this issue still exists then please let me know.
