### ISSUE TITLE
Multi File Support

### ISSUE THREAD

**Issue by PatrickMitchellUI** [stewartmcgown/uds#14]
It would be really useful if a user could add a star (much like linux) to select all files in a dir :)
Just a suggestion

**Comment by de-odex** [comment]
maybe this would be fixed with a port from os.path to pathlib

**Comment by 78Alpha** [comment]
I sort of added this in, it isn't a star perse, but if your file has a period in it you can just do "python uds.py bunch ." And it will upload any file with a "." In it...

**Comment by 78Alpha** [comment]
As of the latest merge, this issue has been fixed and can be now be closed.
