### ISSUE TITLE
Delete not working?

### ISSUE THREAD

**Issue by thrwway1506** [stewartmcgown/uds#20]
My internet connection died in the middle of uploading, so the file did not get uploaded properly, but I can still see it when i run `uds.py list`. So i then run` uds.py delete [file_id]`, but it just returns the `uds.py help` menu, and when i run `list` again, the file is still there.

Could anyone help me understand wether there's anything I am doing wrong?

**Comment by nnoniash** [comment]
The app just would not react to "delete"
PR #21 should now fix this.
