### ISSUE TITLE
ModuleNotFoundError: No module named 'oauth2client'

### ISSUE THREAD

**Issue by kool601** [stewartmcgown/uds#26]
I installed all requirements, and this pops up upon running the script. Windows 10, tried both python 2 and 3, and tried upgrading all the packages. Something's broken I think.

**Comment by kool601** [comment]
Nevermind, I fixed it by running this command: `pip install oauth2client`
Maybe you should add that package to the requirements.

**Comment by 78Alpha** [comment]
Added to a branch and opened a pull request, hopefully that solves the problem

**Comment by rahulbhat44** [comment]
Run this 

sudo python -m pip install oauth2client
