### ISSUE TITLE
Thoughts

### ISSUE THREAD

**Issue by Zibri** [stewartmcgown/uds#31]
Why base64 and doc when we could embed images inside any document? 
How about fuse to make things easier?

**Comment by Zibri** [comment]
Example:

create a 300MB file with random data:
dd if=/dev/urandom of=test.raw bs=300k count=1k
`ffmpeg -f rawvideo -pixel_format rgb24 -video_size 1024x1024 -i test.raw test%03d.png`
[attach the png to a google doc document]
then... unpack the google doc document and
`ffmpeg -i test%03d.png -f rawvideo -pixel_format rgb24 test2.raw`

test,raw and test2.raw  will be the same file.

**Comment by stewartmcgown** [comment]
Extensively covered in #19, these kinds of tricks seem impossible as Google doesn't preserve the image data.

That is, unless you have tested this with a real file and can show it works?

**Comment by Zibri** [comment]
Hmm it sort of works but the file size is now limited... I'll think of something else.. :D
