### ISSUE TITLE
Increase data stored on documents by changing the encoding / formatting?

### ISSUE THREAD

**Issue by berserker465** [stewartmcgown/uds#4]
Hi

Just leaving here a suggestion that someone wrote on reddit.

Would it possible to increase the data stored on every document if the data was encoded in a more complex format (e.g. with text formatting and a different encoding) than base64?

**Comment by stewartmcgown** [comment]
Could be possible to use base85 which has a slightly expanded character set. However, most sources say it isn't really worth the implementation time for the slight gain it offers over bsse64. 

So for now, we stick with bsse64!

**Comment by stewartmcgown** [comment]
![](https://i.imgur.com/fZwkTCQ.jpg) comparison of unicode encoding algorithms

**Comment by stewartmcgown** [comment]
no better alternative to base64 suggested so rip

**Comment by NL9** [comment]
Use yEnc https://en.wikipedia.org/wiki/YEnc

>yEnc's overhead is often as little as 1–2%, compared to 33%–40% overhead for 6-bit encoding methods like uuencode and Base64.

**Comment by stewartmcgown** [comment]
Files encoded with yEnc cannot be convert to Google Docs.
