### ISSUE TITLE
Consider using base85 instead of base64?

### ISSUE THREAD

**Issue by Elronnd** [stewartmcgown/uds#42]
https://en.wikipedia.org/wiki/Ascii85

It's more efficient.

**Comment by stewartmcgown** [comment]
We've been over this on #4 !

Whilst this will give us a 5% storage space decrease, which may be worth it for larger files, I don't plan on changing the implementation right now. If someone wants to submit a pull request which adds an option for it go ahead.

What may be more interesting is a something like base65536, which offers a much better efficiency with unicode text that Google Docs supports.
