### ISSUE TITLE
"Unlimited"?

### ISSUE THREAD

**Issue by singhravi1** [stewartmcgown/uds#43]
Hi,
How is it going to be unlimited?
I think, google docs are still being counted in the 15GB space that a user get?

**Comment by fsc0** [comment]
No, it does not.
![img](https://user-images.githubusercontent.com/49084011/57801368-814ed780-778e-11e9-8c43-f30f11d476e8.jpg)

https://support.google.com/drive/answer/6374270?hl=en

**Comment by stewartmcgown** [comment]
Not an issue :-)

**Comment by singhravi1** [comment]
It says "shared to me".
If it is created by me, then it will be stored on my google drive account and thus take space?

**Comment by fsc0** [comment]
> It says "shared to me".
> If it is created by me, then it will be stored on my google drive account and thus take space?

I think that "...**and** Files in 'Shared with me'" part is not related with other examples (Google Docs, Sheets, Slides, Forms).

Test yourself.
In my side, this brilliant idea works like charm. :)

**Comment by singhravi1** [comment]
Oh okay. Thanks for the clarification :)
