### ISSUE TITLE
is it possible to store the uds file inside the google itself?

### ISSUE THREAD

**Issue by mzramna** [stewartmcgown/uds#46]
acording to your code,if i understand ir right,it need an file to say how the script will build the uploaded file,it is possible to just put this info inside the google spreadsheet and just access this when it runs? like,the file have to be inside the specific google drive location and have specific name,and then using this logic is just necessary to redownload the configuration json and the repository,so it will be avaliable easier when you is not in your own machine

**Comment by stewartmcgown** [comment]
Which configuration files are you suggesting we store? Client ID / Secret?

**Comment by PeterTheHe** [comment]
Think @mzramma is suggesting some key/index/base64 tuple in a sheet. Problem is, said sheets are annoyingly slow to traverse as the number of rows increases - even slower when you're reading out mbs of data (they aren't, to the best of my knowledge, optimised for such scales of data retrieval).

**Comment by stewartmcgown** [comment]
Google Sheets have limitations per cell that make them unsuitable for this
purpose. Check out Google's specs for Sheets and you'll see what I mean

**Comment by stewartmcgown** [comment]
Also, @mzramna, you haven't understood the code if you think we need a file to say how to rebuild the file. The information needed to restore a file is a key value pair attached to each uploaded doc chunk
