### ISSUE TITLE
KeyError: '_module'

### ISSUE THREAD

**Issue by abnx** [stewartmcgown/uds#5]
```
$ python uds.py list
Traceback (most recent call last):
  File "uds.py", line 397, in <module>
    main()
  File "uds.py", line 352, in main
    creds = store.get()
  File "C:\Program Files\Python36\lib\site-packages\oauth2client\client.py", line 407, in get
    return self.locked_get()
  File "C:\Program Files\Python36\lib\site-packages\oauth2client\file.py", line 54, in locked_get
    credentials = client.Credentials.new_from_json(content)
  File "C:\Program Files\Python36\lib\site-packages\oauth2client\client.py", line 302, in new_from_json
    module_name = data['_module']
KeyError: '_module'
```

installed all modules with 'pip install -r requirements.txt'
python 3.6

i generated a credentials.json from the linked google api page and downloaded it to the uds directory. this gave me an error so i renamed it to client_secrets.json like the readme suggests. am i doing something wrong? or it looks like oauth2client has problems? maybe i generated my credentials files wrong since it doesnt contain '_module'? 
pls help

**Comment by DessertArbiter** [comment]
i also get this error

**Comment by stewartmcgown** [comment]
Could be because you named it 'client_secrets' and not 'client_secret'? If not I'll need to look into it more.

**Comment by plato79** [comment]
I also got the same error, and I'm sure it's "client_secret.json"..

**Comment by stewartmcgown** [comment]
Consensus on overflow seems to be that the keyerror is caused by incorrect JSON file. What is the structure of your JSON file? (Without any secrets showing)

**Comment by DessertArbiter** [comment]
i updated it and now it works

**Comment by DessertArbiter** [comment]
i think the reason it wasnt working before was that i didnt run it without arguments first

**Comment by ThatIsAPseudo** [comment]
Note that you may get the same issue if the file is minified ; beautify it and it will work.
