### ISSUE TITLE
Use Google Photos

### ISSUE THREAD

**Issue by avetisk** [stewartmcgown/uds#53]
I don't know how much more efficient this may be, but if you choose to upload your Photos *not* in their original size, Google Photos offers you to store them without taking space from your quota.

There are many different ways this can be used, be it uploading extra tiny 1x1px images with tons of meta-data, or using QR code like encoding.

Just my 2¢ 🙏

**Comment by stewartmcgown** [comment]
Covered at length in #19.

TL;DR no benefit in speed, worse API, ruins the usability of Google Photos for the account it used on.
