### ISSUE TITLE
 C version

### ISSUE THREAD

**Issue by bialy10Ok** [stewartmcgown/uds#56]
Is planing to create C lib for other languages? Ruby, Haskell, Rust?
After stabilise API of course.

Meybe in future storing dat on other places. What You thing about pastebin, forums, comment in blogs or news?

**Comment by SammyHass** [comment]
No doubt in my mind that others will make this other tools. It’s an awesomely smart idea with a pretty straight forward execution. Why don’t you do it?

**Comment by stewartmcgown** [comment]
I learned Python from scratch by building this project, so I don't see why I couldn't do the same with rust or ruby. I can already code in C and Haskell, but I don't see a need for 'libraries' as such with this app. UDS is just a command line tool, and I don't plan for it to be included in something like 'libUDS'.

Remember, all my app does is convert binary to base64 and upload it to Google Docs. 

Note: Originally, this project was in JS.

https://github.com/PeterTheHe/Unlimited-Drive-Storage

So technically it's already written in another language!
