### ISSUE TITLE
GUI around the tool

### ISSUE THREAD

**Issue by motatoes** [stewartmcgown/uds#58]
Beautiful idea! I'm not sure how long this will last, but do you think it's worth building a GUI around your cli? It will include the flow of authorising with google drive and then have a tray icon with folder watching like the dropbox app :)

I'm thinking of making a start on this. What do you think?

**Comment by skvie** [comment]
Nice idea, but I personally don't see a benefit in it.

**Comment by PeterTheHe** [comment]
A very crappy basic one can be found here implemented in Google Apps Script. Feel free to break/improve.

https://nuget.pkg.github.com/PeterTheHe/Unlimited-Drive-Storag

**Comment by SammyHass** [comment]
Remember that e! 
https://nuget.pkg.github.com/PeterTheHe/Unlimited-Drive-Storage

❤️

**Comment by stewartmcgown** [comment]
Google apps script holy shit

What a flashback 😭

**Comment by motatoes** [comment]
Oh thanks for the link @SammyHass , I'm thinking of using QT (either Python or C++). I think it will be useful for non techies who want to make use of this hole :D [depending on how long google takes to fix]

**Comment by SammyHass** [comment]
Closing as the README now as @stewartmcgown is in development of web based version (link in README)
