### ISSUE TITLE
Invalid Syntax Line 219

### ISSUE THREAD

**Issue by JaredRCooper** [stewartmcgown/uds#6]
At first I had a error "Syntax Error: Non-ASCII Character '/ex2' in file uds.py on line 183, but no encoding declared".

I added `# -*- coding: utf-8 -*-` to the top and that fixed that error.

The second error I am having is "File "uds.py", line 219 path = f"{get_downloads_folder()}/{metadata['name']}"^.

I attached screen shots.

First error : https://imgur.com/MFmWwvP

Second error : https://imgur.com/CQXrc4T

**Comment by cclauss** [comment]
You only need the encoding lines in Python 2.  This project only supports Python 3 which has a default Python file encoding of utf-8 so those lines are no longer required.

**Comment by stewartmcgown** [comment]
I've let you merge it cause it doesn't make anything break, but my boy @cclauss is right
