### ISSUE TITLE
Pull bug?

### ISSUE THREAD

**Issue by penjune** [stewartmcgown/uds#61]
After pushing files smaller than 4KB ,
I want to pull these files to check if they were corrupted or not.
And I found that there was bug when pulling files smaller than approximately 4KB. (original size)

Here are the error messages : 
Failed to verify hash ,
Downloaded file had hash %s compared to original %s ('e3b0c4429', '99d00379f')

By the way, all the files larger than 4KB I pulled didn't have the hash problem.

**Comment by mihirk11** [comment]
Looks like #60

**Comment by SammyHass** [comment]
Fixed in #63
