### ISSUE TITLE
Issue running initial setup

### ISSUE THREAD

**Issue by Zeniic** [stewartmcgown/uds#64]
Hello, 

I am having an issue running the following command: `python uds.py`

I have made sure to install the requirements and have imported my credentials as the requested filename.. Am I missing something? 

Here is my error: 
```  
File "uds.py", line 60
    print("", end='')
                 ^
SyntaxError: invalid syntax
```

**Comment by SammyHass** [comment]
That's odd, will look into it and find out what's going on. Thanks for reporting.

**Comment by Zeniic** [comment]
Thank you. 
I'm guessing it's something my end because other people seem to be having positive results. 

Do you have any recommendations for environment? (Such as OS, Python Version etc)

**Comment by SammyHass** [comment]
What OS are you on and what version are you on? This only supports Python 3 and ```python``` is often running python 2, for example. Running scripts with ```python``` on mac loads python 2. You will have to run ```python3 uds.py``` to run python 3. This would mean setup is:
```
pip3 install -r requirements.txt
python3 uds.py
```

**Comment by Zeniic** [comment]
I'm running Debian 9.4. 

Looks like I was at fault as I thought. 
Followed the same steps but this time under Python 3 and everything seems to be working (As far as Initial setup goes)

For noobs like me you should drop that info into the README to prevent further issues.

Thank you

**Comment by SammyHass** [comment]
Aha - no worries.
It is at the bottom of README.md, but I will add a custom exception in Python to alert of wrong version.

Thanks for reporting.
