### ISSUE TITLE
tqdm arguments issue

### ISSUE THREAD

**Issue by joeborrello** [stewartmcgown/uds#65]
Everything installed and initialized correctly, however, when I try to `push` a file I get an error that appears to be stemming from tqdm not recognizing the `position` argument. Not sure if this is an issue with the version of tqdm I'm using (2.2.3).

**Comment by SammyHass** [comment]
Probably is, please install requirements.txt file with pip. As it is running on 4.31. This will be your issue.

**Comment by joeborrello** [comment]
Yep, that did it. Thanks!
