### ISSUE TITLE
table of User.txt

### ISSUE THREAD

**Issue by penjune** [stewartmcgown/uds#68]
Without wcwidth , table of my User.txt couldn't be aligned correctly.

Before installing wcwidth : 
![image](https://i.imgur.com/yq1uCiy.png)

After : 
![image](https://i.imgur.com/2ghn2Nd.png)

**Comment by SammyHass** [comment]
Ah, good find! Please create a pull request to fix this issue. I need more details about it too in order to understand properly. Please would you add the file User.txt to the pull request.

Thanks for helping out!

**Comment by SammyHass** [comment]
Is this output from ```cat``` ?

**Comment by penjune** [comment]
Both output from python3 uds.py list.
I found several articles saying tabulate would generate incorrectly-aligned table when there
were non-english characters in the table, and these articles said wcwidth would help solve this probelm.
Actually I do not know the exact reason why tabulate would malfunction with non-english characters. 
And I am a beginner of github , so could you pull request by yourself?
Thanks.

**Comment by SammyHass** [comment]
Yeah sure (just thought you might want the credit! 😃), thanks for your help!

**Comment by SammyHass** [comment]
Fixed in 4c94abc.

Thanks
