### ISSUE TITLE
[BUG] Google Login?

### ISSUE THREAD

**Issue by Knight1** [stewartmcgown/uds#76]
**Describe the bug**
Downloaded client_secret.json, it is showing me some Google Login Screen..

**Expected behavior**
It is uploading files when using push but instead it is asking for credentials.json and uds.py is showing me the screen below.

**System Information**
Python Version 3.5.3, OS Debian 9.9

<img width="1418" alt="image" src="https://user-images.githubusercontent.com/1573278/59003227-5e579680-8815-11e9-99b9-5e00d013f928.png">

**Comment by stewartmcgown** [comment]
because you must log in with a Google Account in order to authorise your client_secret.json

It looks like the oauth2client package thinks that your browser is Lynx or some other command line browser. Can you change your default browser in Debian to something that works with Google sign in?
