### ISSUE TITLE
 ERROR: Command errored out with exit status 1[BUG]

### ISSUE THREAD

**Issue by dkb007** [stewartmcgown/uds#87]
**Describe the bug**
The bug happens in Windows 10 Power Shell as I tried to install the requirements using the command line : pip3 install -r requirements.txt 

**To Reproduce**
1. Extract the UDS folder from zip to desktop
2. Copy the client_secret.json to UDS folder
3. Open the PowerShell by pressing the Shift key and right click inside the UDS folder
4. run the command : pip3 install -r requirements.txt

**Expected behavior**
I thought that the requirements will be installed without any error or warnings.

**Screenshots**
I cannot provide screenshot as the error message is too big to fit inside a Screenshot so I'm just Copy-pasting the error code : 

//Error 
ERROR: Command errored out with exit status 1:
     command: 'c:\users\devarsh\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Devarsh\\AppData\\Local\\Temp\\pip-install-pgj6qxin\\cryptography\\setup.py'"'"'; __file__='"'"'C:\\Users\\Devarsh\\AppData\\Local\\Temp\\pip-install-pgj6qxin\\cryptography\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Devarsh\AppData\Local\Temp\pip-record-s9vioxe3\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\Devarsh\AppData\Local\Temp\pip-install-pgj6qxin\cryptography\
    Complete output (103 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.8
    creating build\lib.win32-3.8\cryptography
    copying src\cryptography\exceptions.py -> build\lib.win32-3.8\cryptography
    copying src\cryptography\fernet.py -> build\lib.win32-3.8\cryptography
    copying src\cryptography\utils.py -> build\lib.win32-3.8\cryptography
    copying src\cryptography\__about__.py -> build\lib.win32-3.8\cryptography
    copying src\cryptography\__init__.py -> build\lib.win32-3.8\cryptography
    creating build\lib.win32-3.8\cryptography\hazmat
    copying src\cryptography\hazmat\__init__.py -> build\lib.win32-3.8\cryptography\hazmat
    creating build\lib.win32-3.8\cryptography\x509
    copying src\cryptography\x509\base.py -> build\lib.win32-3.8\cryptography\x509
    copying src\cryptography\x509\certificate_transparency.py -> build\lib.win32-3.8\cryptography\x509
    copying src\cryptography\x509\extensions.py -> build\lib.win32-3.8\cryptography\x509
    copying src\cryptography\x509\general_name.py -> build\lib.win32-3.8\cryptography\x509
    copying src\cryptography\x509\name.py -> build\lib.win32-3.8\cryptography\x509
    copying src\cryptography\x509\oid.py -> build\lib.win32-3.8\cryptography\x509
    copying src\cryptography\x509\__init__.py -> build\lib.win32-3.8\cryptography\x509
    creating build\lib.win32-3.8\cryptography\hazmat\backends
    copying src\cryptography\hazmat\backends\interfaces.py -> build\lib.win32-3.8\cryptography\hazmat\backends
    copying src\cryptography\hazmat\backends\__init__.py -> build\lib.win32-3.8\cryptography\hazmat\backends
    creating build\lib.win32-3.8\cryptography\hazmat\bindings
    copying src\cryptography\hazmat\bindings\__init__.py -> build\lib.win32-3.8\cryptography\hazmat\bindings
    creating build\lib.win32-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\cmac.py -> build\lib.win32-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\constant_time.py -> build\lib.win32-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\hashes.py -> build\lib.win32-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\hmac.py -> build\lib.win32-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\keywrap.py -> build\lib.win32-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\mac.py -> build\lib.win32-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\padding.py -> build\lib.win32-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\serialization.py -> build\lib.win32-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\__init__.py -> build\lib.win32-3.8\cryptography\hazmat\primitives
    creating build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\aead.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\backend.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\ciphers.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\cmac.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\decode_asn1.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\dh.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\dsa.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\ec.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\encode_asn1.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\hashes.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\hmac.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\rsa.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\utils.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\x25519.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\x509.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\__init__.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    creating build\lib.win32-3.8\cryptography\hazmat\bindings\openssl
    copying src\cryptography\hazmat\bindings\openssl\binding.py -> build\lib.win32-3.8\cryptography\hazmat\bindings\openssl
    copying src\cryptography\hazmat\bindings\openssl\_conditional.py -> build\lib.win32-3.8\cryptography\hazmat\bindings\openssl
    copying src\cryptography\hazmat\bindings\openssl\__init__.py -> build\lib.win32-3.8\cryptography\hazmat\bindings\openssl
    creating build\lib.win32-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\dh.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\dsa.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\ec.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\padding.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\rsa.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\utils.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\x25519.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\__init__.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\asymmetric
    creating build\lib.win32-3.8\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\aead.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\algorithms.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\base.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\modes.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\__init__.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\ciphers
    creating build\lib.win32-3.8\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\concatkdf.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\hkdf.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\kbkdf.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\pbkdf2.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\scrypt.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\x963kdf.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\__init__.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\kdf
    creating build\lib.win32-3.8\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\hotp.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\totp.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\utils.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\__init__.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\twofactor
    running egg_info
    writing src\cryptography.egg-info\PKG-INFO
    writing dependency_links to src\cryptography.egg-info\dependency_links.txt
    writing requirements to src\cryptography.egg-info\requires.txt
    writing top-level names to src\cryptography.egg-info\top_level.txt
    reading manifest file 'src\cryptography.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs\_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
    writing manifest file 'src\cryptography.egg-info\SOURCES.txt'
    running build_ext
    generating cffi module 'build\\temp.win32-3.8\\Release\\_padding.c'
    creating build\temp.win32-3.8
    creating build\temp.win32-3.8\Release
    generating cffi module 'build\\temp.win32-3.8\\Release\\_constant_time.c'
    generating cffi module 'build\\temp.win32-3.8\\Release\\_openssl.c'
    building '_openssl' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\devarsh\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Devarsh\\AppData\\Local\\Temp\\pip-install-pgj6qxin\\cryptography\\setup.py'"'"'; __file__='"'"'C:\\Users\\Devarsh\\AppData\\Local\\Temp\\pip-install-pgj6qxin\\cryptography\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Devarsh\AppData\Local\Temp\pip-record-s9vioxe3\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**System Information**
Python Version : latest from the website Python 3.8.0. 
OS : Windows 10 (1909) Anything that may help

**Comment by stewartmcgown** [comment]
See at the end how it says 'Microsoft Build Tools are required'? Have you
tried installing Microsoft Build Tools?

**Comment by dkb007** [comment]
But why should I download and install Visual Studio 2019 (I have VSCode). Is there any specific reason?

**Comment by dkb007** [comment]
Can you also give a detail description on how to use the JS version of this service? I mean how do I declare my own API and id in that JS version? Please Give me a Detail Description or any video on how to install that JS version and start up running it! that would be really helpful

**Comment by stewartmcgown** [comment]
Because the error output says to, so install Microsoft Build tools and the
problem will go away.

VSCode is a text editor and does not include any of the features needed to
compile the python modules.

**Comment by dkb007** [comment]
Nope still getting some errors :( Installed Visual Studio with the Build tools and all but still getting this error : 

//Error 

ERROR: Command errored out with exit status 1:
     command: 'c:\users\devarsh\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Devarsh\\AppData\\Local\\Temp\\pip-install-b7fpy3o8\\cryptography\\setup.py'"'"'; __file__='"'"'C:\\Users\\Devarsh\\AppData\\Local\\Temp\\pip-install-b7fpy3o8\\cryptography\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Devarsh\AppData\Local\Temp\pip-record-mjmilj53\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\Devarsh\AppData\Local\Temp\pip-install-b7fpy3o8\cryptography\
    Complete output (109 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.8
    creating build\lib.win32-3.8\cryptography
    copying src\cryptography\exceptions.py -> build\lib.win32-3.8\cryptography
    copying src\cryptography\fernet.py -> build\lib.win32-3.8\cryptography
    copying src\cryptography\utils.py -> build\lib.win32-3.8\cryptography
    copying src\cryptography\__about__.py -> build\lib.win32-3.8\cryptography
    copying src\cryptography\__init__.py -> build\lib.win32-3.8\cryptography
    creating build\lib.win32-3.8\cryptography\hazmat
    copying src\cryptography\hazmat\__init__.py -> build\lib.win32-3.8\cryptography\hazmat
    creating build\lib.win32-3.8\cryptography\x509
    copying src\cryptography\x509\base.py -> build\lib.win32-3.8\cryptography\x509
    copying src\cryptography\x509\certificate_transparency.py -> build\lib.win32-3.8\cryptography\x509
    copying src\cryptography\x509\extensions.py -> build\lib.win32-3.8\cryptography\x509
    copying src\cryptography\x509\general_name.py -> build\lib.win32-3.8\cryptography\x509
    copying src\cryptography\x509\name.py -> build\lib.win32-3.8\cryptography\x509
    copying src\cryptography\x509\oid.py -> build\lib.win32-3.8\cryptography\x509
    copying src\cryptography\x509\__init__.py -> build\lib.win32-3.8\cryptography\x509
    creating build\lib.win32-3.8\cryptography\hazmat\backends
    copying src\cryptography\hazmat\backends\interfaces.py -> build\lib.win32-3.8\cryptography\hazmat\backends
    copying src\cryptography\hazmat\backends\__init__.py -> build\lib.win32-3.8\cryptography\hazmat\backends
    creating build\lib.win32-3.8\cryptography\hazmat\bindings
    copying src\cryptography\hazmat\bindings\__init__.py -> build\lib.win32-3.8\cryptography\hazmat\bindings
    creating build\lib.win32-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\cmac.py -> build\lib.win32-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\constant_time.py -> build\lib.win32-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\hashes.py -> build\lib.win32-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\hmac.py -> build\lib.win32-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\keywrap.py -> build\lib.win32-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\mac.py -> build\lib.win32-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\padding.py -> build\lib.win32-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\serialization.py -> build\lib.win32-3.8\cryptography\hazmat\primitives
    copying src\cryptography\hazmat\primitives\__init__.py -> build\lib.win32-3.8\cryptography\hazmat\primitives
    creating build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\aead.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\backend.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\ciphers.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\cmac.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\decode_asn1.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\dh.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\dsa.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\ec.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\encode_asn1.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\hashes.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\hmac.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\rsa.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\utils.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\x25519.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\x509.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    copying src\cryptography\hazmat\backends\openssl\__init__.py -> build\lib.win32-3.8\cryptography\hazmat\backends\openssl
    creating build\lib.win32-3.8\cryptography\hazmat\bindings\openssl
    copying src\cryptography\hazmat\bindings\openssl\binding.py -> build\lib.win32-3.8\cryptography\hazmat\bindings\openssl
    copying src\cryptography\hazmat\bindings\openssl\_conditional.py -> build\lib.win32-3.8\cryptography\hazmat\bindings\openssl
    copying src\cryptography\hazmat\bindings\openssl\__init__.py -> build\lib.win32-3.8\cryptography\hazmat\bindings\openssl
    creating build\lib.win32-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\dh.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\dsa.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\ec.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\padding.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\rsa.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\utils.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\x25519.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\asymmetric
    copying src\cryptography\hazmat\primitives\asymmetric\__init__.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\asymmetric
    creating build\lib.win32-3.8\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\aead.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\algorithms.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\base.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\modes.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\ciphers
    copying src\cryptography\hazmat\primitives\ciphers\__init__.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\ciphers
    creating build\lib.win32-3.8\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\concatkdf.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\hkdf.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\kbkdf.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\pbkdf2.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\scrypt.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\x963kdf.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\kdf
    copying src\cryptography\hazmat\primitives\kdf\__init__.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\kdf
    creating build\lib.win32-3.8\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\hotp.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\totp.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\utils.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\twofactor
    copying src\cryptography\hazmat\primitives\twofactor\__init__.py -> build\lib.win32-3.8\cryptography\hazmat\primitives\twofactor
    running egg_info
    writing src\cryptography.egg-info\PKG-INFO
    writing dependency_links to src\cryptography.egg-info\dependency_links.txt
    writing requirements to src\cryptography.egg-info\requires.txt
    writing top-level names to src\cryptography.egg-info\top_level.txt
    reading manifest file 'src\cryptography.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs\_build'
    warning: no previously-included files matching '*' found under directory 'vectors'
    writing manifest file 'src\cryptography.egg-info\SOURCES.txt'
    running build_ext
    generating cffi module 'build\\temp.win32-3.8\\Release\\_padding.c'
    creating build\temp.win32-3.8
    creating build\temp.win32-3.8\Release
    generating cffi module 'build\\temp.win32-3.8\\Release\\_constant_time.c'
    generating cffi module 'build\\temp.win32-3.8\\Release\\_openssl.c'
    building '_openssl' extension
    creating build\temp.win32-3.8\Release\build
    creating build\temp.win32-3.8\Release\build\temp.win32-3.8
    creating build\temp.win32-3.8\Release\build\temp.win32-3.8\Release
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\devarsh\appdata\local\programs\python\python38-32\include -Ic:\users\devarsh\appdata\local\programs\python\python38-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcbuild\temp.win32-3.8\Release\_openssl.c /Fobuild\temp.win32-3.8\Release\build\temp.win32-3.8\Release\_openssl.obj
    _openssl.c
    build\temp.win32-3.8\Release\_openssl.c(498): fatal error C1083: Cannot open include file: 'openssl/opensslv.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\devarsh\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Devarsh\\AppData\\Local\\Temp\\pip-install-b7fpy3o8\\cryptography\\setup.py'"'"'; __file__='"'"'C:\\Users\\Devarsh\\AppData\\Local\\Temp\\pip-install-b7fpy3o8\\cryptography\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Devarsh\AppData\Local\Temp\pip-record-mjmilj53\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by stewartmcgown** [comment]
But it is a different error, so things are getting better! Have you googled
the new error?

**Comment by dkb007** [comment]
I tried to find it on google but no clue on this one :(

**Comment by stewartmcgown** [comment]
This is the first result on Google when I search for that error.

https://stackoverflow.com/q/37951303/1255271

Not a bug.
